language: python

python:
    - 2.7
    - 3.4

sudo: false

before_install:
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.44-1.linux-64.sh
    - sh lilypond-2.19.44-1.linux-64.sh --batch
    - export PATH=/home/travis/bin:$PATH
    - git clone https://github.com/Abjad/abjad.git && cd abjad && git checkout josiah/dev && pip install -e .[development,ipython] && cd ..
    - pip install coveralls
    - pip install coverage
    - ls . && pwd

install:
    - pip install -e . 

script:
    - coverage run -a `which ajv` doctest ./consort
    - coverage run -a `which py.test` -rf ./consort

after_success:
    coveralls

notifications:
    email: false
