language: python

python:
    - 2.7

install:
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - py.test -rf ./consort
    - ajv dt ./consort

notifications:
    email: false