language: python

python:
    - 2.7
    - 3.4

install:
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - ajv doctest ./consort
    - py.test -rf ./consort

notifications:
    email: false